## Import the relevant libraries

In [1]:
import numpy as np

## Declaring scalars, vectors, and matrices

### Scalars

In [2]:
# Define the integer
s = 5

In [3]:
s

5

### Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
# By default v would be a row vector
v

array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [8]:
# type(a) return the data type of a given
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
# Change to an array for s
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

### Data shape

In [13]:
# shape returns the shape (dimensions) of a variable
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [15]:
s.shape # Error is normal since s is not an array

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape

()

#### Creatin a colum vector

In [17]:
# reshape gives an array a new shape, without changing its data
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])