## Import the relevant libraries

In [1]:
import numpy as np

## Creating a tensor

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
# Creating a 3D tensor
t = np.array([m1,m2])

In [5]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Checking its shape

In [6]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [7]:
# Tensor manually
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

In [8]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Addition

In [9]:
# Definiting matix one
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [10]:
# Definiting matix otwo
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [11]:
# Add to matrices
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

## Difference

In [12]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [13]:
m3

array([[ 5,  3],
       [-2,  4]])

In [14]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [15]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

## Adding vectors together

In [16]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [17]:
v1 + v2

array([6, 6, 6, 6, 6])

In [18]:
v1 - v2

array([-4, -2,  0,  2,  4])