# Train Test Split

## Import the relevant liberaries

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to splt

In [2]:
# Arange values 
a = np.arange(1,101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501, 601)

In [5]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the Data

In [6]:
# Split array or matices
train_test_split(a)

[array([ 96,  13,  95,  81,   4,  92,   2,   8,  16,   3,  51,  14,  21,
         70,  80,  53,  26,  54,  38,  79,  87,  69,   9,  24,  29,  42,
         61,  17,  88,  49,  22,  31,  32,  85,  25,  39,  56,  50,  27,
         97,  68,  15,  34, 100,  67,  43,  65,  63,  91,  37,  40,  89,
         10,  36,  62,   6,  94,  75,  64,  99,  11,  45,  19,  33,  58,
         93,  60,  73,  74,  35,   5,  71,  30,  86,  59]),
 array([47, 23, 20, 78, 66, 76, 48, 55, 44, 41, 82, 18, 46, 52, 98, 28, 83,
        84, 72,  7, 77, 12, 57,  1, 90])]

In [52]:
# Store the result
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)

## Explore the result

In [46]:
# Check Result
a_train.shape, a_test.shape

((80,), (20,))

In [47]:
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [48]:
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

### Split more than one array at the same time

In [54]:
b_train.shape, b_test.shape

((80,), (20,))

In [55]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [56]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])