## Mutiple linear regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

### Load data

In [6]:
data = pd.read_csv('1.02. Multiple linear regression.csv')

# Display the first 4
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [9]:
# DEscribe the data aquired
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Create the multiple linear regression

### Declare the dependent and independent variable

In [12]:
# Indepedent variable
x = data[['SAT','Rand 1,2,3']]

# Dependent variable
y = data['GPA']

### Regression itself

In [15]:
# Instance of linear regression class
reg = LinearRegression()

# Fit the Linear Regression
reg.fit(x,y)

LinearRegression()

In [17]:
# Display coeffiecient
reg.coef_

array([ 0.00165354, -0.00826982])

In [19]:
# Display the intercept
reg.intercept_

0.29603261264909353

## Calculating the R-Square

In [23]:
# score return the R-square
reg.score(x,y)

0.4066811952814282

### Formula for adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)\frac{n-1}{n-p-1}$

In [26]:
# Shape of x
x.shape

(84, 2)

### Solution

$R^2_{adj.} = 1 - (1-R^2)\frac{84-1}{84-2-1}$

$R^2_{adj.} = 1 - (1-R^2)\frac{83}{81}$

$R^2_{adj.} = R^2\frac{83}{81}$

In [30]:
r2 = reg.score(x,y)

# Parameters
n = x.shape[0]
p = x.shape[1]

In [32]:
# Adjusted R-square calculation
adj_R2 = 1 - (1 - r2)*((n-1)/(n-p-1))
adj_R2

0.39203134825134

## Feature selection

In [34]:
from sklearn.feature_selection import f_regression

In [37]:
#F-Regression 
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [40]:
#P-Values
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [42]:
# Round values
p_values.round(3)

array([0.   , 0.676])

## Creating a summary table

In [43]:
# Create data frame
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [48]:
# New series of Data frame
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676